<?php
/** @var $block \ADM\QuickDevBar\Block\Tab\Content\Layout */
?>
<?php if ($block->getBlocks()):?>
<table class="qdn_table striped filterable">
<thead>
<tr>
    <th>Block</th>
    <th>Call Number</th>
</tr>
</thead>
<tbody>
    <?php
    $i = 0;
    foreach ($block->getBlocks() as $blockInfo): ?>
  <tr>
    <td><?php echo $blockInfo['class']; ?></td>
    <td><?php echo $blockInfo['nbr']; ?></td>
  </tr>
        <?php $i++; ?>
    <?php endforeach ?>
</tbody>
</table>
<?php endif;?>