<?php
/** @var \ADM\QuickDevBar\Block\Tab\Content\Cache $block */
?>
<?php if ($block->getCacheList()):?>
<table class="qdn_table striped filterable">
<thead>
<tr>
    <th>Identifier</th>
    <th>Save</th>
    <th>Load</th>
    <th>Remove</th>
</tr>
</thead>
<tbody>
    <?php foreach ($block->getCacheList() as $identifier=>$events): ?>
      <tr>
          <td><?=  $identifier; ?></td>
          <td><?=  $events['save']; ?></td>
        <td><?=  $events['load']; ?></td>
        <td><?=  $events['remove']; ?></td>
      </tr>
    <?php endforeach ?>
</tbody>
</table>
<?php endif;?>
