<?php
/** @var \ADM\QuickDevBar\Block\Tab\Panel $block */

//TODO: Add view cache
//TODO: Add all cache type
?>
<?php if ($block->getCacheEvents()):?>
<table class="qdb_table striped filterable">
<thead>
<tr>
    <th>Identifier</th>
    <th>Save</th>
    <th>Load</th>
    <th>Remove</th>
</tr>
</thead>
<tbody>
    <?php foreach ($block->getCacheEvents() as $identifier=>$events): ?>
      <tr>
          <td><?=  $identifier; ?></td>
          <td><?=  $events['save']; ?></td>
        <td><?=  $events['load']; ?></td>
        <td><?=  $events['remove']; ?></td>
      </tr>
    <?php endforeach ?>
</tbody>
</table>
<?php endif;?>
