<?php
?>
<?php if($this->getCollections()):?>
<table class="qdn_collection qdn_table striped filterable sortable tablesorter">
<thead>
<tr>
    <th>Collection</th>
    <th>Call Number</th>
</tr>
</thead>
<tbody>
<?php
  $i = 0;
  foreach ($this->getCollections() as $collection): ?>
  <tr>
    <td><?php echo $collection['class']; ?></td>
    <td><?php echo $collection['nbr']; ?></td>
  </tr>
    <?php $i++; ?>
  <?php endforeach ?>
</tbody>
</table>
<?php endif;?>