<?php
?>
<table class="qdn_plugin qdn_table striped filterable sortable tablesorter">
<thead>
<tr>
    <th>Types</th>
    <th>Plugin</th>
    <th>Sort Order</th>
    <th>Method</th>
</tr>
</thead>
<tbody>
<?php
  foreach ($block->getPluginsList() as $type): ?>
    <tr>
      <td class="type"><?php echo $type['type']; ?></td>
      <td class="plugin"><?php echo $type['plugin']; ?></td>
      <td class="sort_order"><?php echo $type['sort_order']; ?></td>
      <td class="methods"><?php echo $type['method']; ?></td>
    </tr>
  <?php endforeach ?>
</tbody>
</table>