<?php
?>
<table class="qdn_plugin qdn_table striped filterable sortable tablesorter">
<thead>
<tr>
    <th>Types</th>
    <th>Plugin</th>
    <th>Sort Order</th>
    <th>Method</th>
</tr>
</thead>
<tbody>
<?php
foreach ($block->getPluginsList() as $type): ?>
    <tr>
      <td class="type"><?=  $type['type']; ?></td>
      <td class="plugin"><?=  $type['plugin']; ?></td>
      <td class="sort_order"><?=  $type['sort_order']; ?></td>
      <td class="methods"><?=  $type['method']; ?></td>
    </tr>
    <?php endforeach ?>
</tbody>
</table>