<?php
/**  @var \ADM\QuickDevBar\Block\Tab\Content\Preference $block*/
?>
Display only preferences cross modules
<table class="qdn_plugin qdn_table striped filterable sortable tablesorter">
<thead>
<tr>
    <th>Types</th>
    <th>Preferences</th>
</tr>
</thead>
<tbody>
<?php
foreach ($block->getPreferencesList() as $type =>$preference): ?>
    <tr>
        <td><?= $type ?></td>
        <td><?= $preference ?></td>
    </tr>
    <?php endforeach ?>
</tbody>
</table>