<?php
/** @var  $block \ADM\QuickDevBar\Block\Tab\Panel */
?>
<div id="qdn-profiler-container">
<?=  __('Cannot find profiler table or profiler is not enabled.'); ?>
<br/>
Since 2.3 you can enable the profiler with the following command
<pre>bin/magento dev:profiler:enable html</pre>
You have to add a SetEnv MAGE_PROFILER "html" to your .htaccess (do not use "csvfile" nor "firebug" to have profiler displayed in tab).<br/>
Be careful with .htacces directives an redirection you can have <br/>
<pre>$_SERVER['REDIRECT_MAGE_PROFILER']</pre>
setted instead of<br/>
<pre>$_SERVER['MAGE_PROFILER']</pre>
prefer apache2.conf.
<br/><br/>
You can read the official documentation <a href="http://devdocs.magento.com/guides/v2.1/config-guide/bootstrap/mage-profiler.html">Enable profiling (MAGE_PROFILER)</a>
</div>

<script type="text/javascript">
        [...document.querySelectorAll('caption')].forEach(elem => {
            if (elem.firstChild.data.match(/Code Profiler \(Memory usage: real - \d+, emalloc - \d+\)/)) {

                const qdnProfilerContainer = document.getElementById('qdn-profiler-container');
                qdnProfilerContainer.innerHTML = '';

                let profilerTable = elem.parentNode;
                profilerTable.removeAttribute('border');
                profilerTable.removeAttribute('cellspacing');
                profilerTable.removeAttribute('cellpadding');
                profilerTable.classList.add("qdb_table", "filterable", "sortable", "striped");

                qdnProfilerContainer.appendChild(profilerTable);
            }
        })
</script>
