<?php if ($this->getTranslations()):?>
    <table class="qdn_table striped filterable">
        <thead>
        <tr>
            <th>Original</th>
            <th>Translation</th>
        </tr>
        </thead>
        <tbody>
        <?php
        $i = 0;
        foreach ($this->getTranslations() as $original => $translation): ?>
            <tr>
                <td><?=  $original; ?></td>
                <td><?=  $translation; ?></td>
            </tr>
            <?php $i++; ?>
        <?php endforeach ?>
        </tbody>
    </table>
<?php endif;?>
