<?php
?>
<p>
<?php echo __('List only events dispatched when Magento generate this page')?>
</p>
<?php if($this->getEvents()):?>
<table class="qdn_table striped filterable">
<thead>
<tr>
    <th>Event</th>
</tr>
</thead>
<tbody>
<?php
  $i = 0;
  foreach ($this->getEvents() as $event): ?>
  <tr style="border: 1px solid black">
    <td><?php echo $event['event']; ?></td>
  </tr>
    <?php $i++; ?>
  <?php endforeach ?>
</tbody>
</table>
<?php endif;?>