<?php
?>
<p>
<?php echo __('List only observer that intercept dispatched events when Magento generate this page')?>
</p>
<table class="qdn_table">
<tr>
    <th>Event</th>
    <th>Name</th>
    <th>Call Number</th>
    <th>Method</th>
    <th>Class</th>
</tr>
<?php
  $i = 0;
  foreach ($this->getObservers() as $observer): ?>
  <tr class="<?php echo ($i % 2 ? 'even' : 'odd')?>">
    <td><?php echo $observer['event']; ?></td>
    <td><?php echo $observer['name']; ?></td>
    <td><?php echo $observer['call_number']; ?></td>
    <td><?php echo $observer['method']; ?></td>
    <td><?php echo $observer['instance']; ?></td>
  </tr>
    <?php $i++; ?>
  <?php endforeach ?>
</table>