<?php
//$_helper = Mage::helper('wee_developertoolbar');
$_profiler = $block->getSqlProfiler();
?>
<?php if ($block->getQueryProfiles()): ?>
<table class="qdn_table_2col">
  <tr>
    <th><?php echo __('Executed'); ?></th>
    </td>
    <td>
      <?php echo sprintf('%s queries in %s seconds', $_profiler->getTotalNumQueries(), $_profiler->getTotalElapsedSecs()); ?>
    </td>
  </tr>
  <tr>
    <th><?php echo __('Average query length'); ?></th>
    <td>
      <?php echo sprintf('%s seconds', $_profiler->getTotalNumQueries() &&  $_profiler->getTotalElapsedSecs() ? $_profiler->getTotalElapsedSecs()/$_profiler->getTotalNumQueries() : 0); ?>
    </td>
  </tr>
  <tr>
    <th><?php echo __('Queries per second'); ?></th>
    <td>
      <?php echo ($_profiler->getTotalNumQueries() && $_profiler->getTotalElapsedSecs() ?  $_profiler->getTotalNumQueries()/$_profiler->getTotalElapsedSecs() : 0); ?>
    </td>
  </tr>
  <tr>
    <th><?php echo __('Longest query length'); ?></th>
    <td>
      <?php echo $block->getLongestQueryTime(); ?>
    </td>
  </tr>
  <tr>
    <th><?php echo __('Longest query'); ?></th>
    <td>
      <?php echo $block->formatSql($block->getLongestQuery()); ?>
    </td>
  </tr>
</table>

<table class="qdn_table striped filterable">
<tbody>
<?php
  $i = 0;
  foreach ($block->getQueryProfiles() as $query): ?>
    <tr>
      <td><?php echo $block->formatSql($query->getQuery()); ?>
      <span class="sqlinfo">
      <?php echo __('Elapsed seconds:'); ?> <?php echo $query->getElapsedSecs() ?>
      </span>
      </td>
    </tr>
    <?php $i++; ?>
  <?php endforeach ?>
</tbody>
</table>


<?php else:?>
SQL profiler is not active<br/>
You should set a new key for $config array in file app/etc/env.php<br/>
$config[db][connection][default][profiler] = 1
<?php  endif ?>