<?php if($block->isUserAllowed()):?>
<div>
<div id="qdb-bar" style="display: none;" data-mage-init='{"quickDevBar":{"toggleEffect":"drop"}}'>
<?php echo $block->getChildHtml(); ?>
</div>
<div id="qdb-bar-anchor">
<img src="<?php echo $block->getViewFileUrl('ADM_QuickDevBar::images/qdb-icon.png') ?>" alt="<?php echo __('QuickDevBar'); ?>" title="<?php echo __('Click to toggle the Quick Development Toolbar'); ?>"/>&nbsp;
</div>
</div>
<?php endif;?>