<?php
/** @var  $block \ADM\QuickDevBar\Block\Tab\Panel */
?>
<p>
<?=  __('List config for default scope')?>
</p>
<?php if ($block->getConfigValues()):?>
<table class="qdb_table striped filterable sortable">
<thead>
<tr>
    <th>Path</th>
    <th>Value</th>
</tr>
</thead>
<tbody>
    <?php
    $i = 0;
    foreach ($block->getConfigValues() as $config): ?>
  <tr>
    <td><?=  $config['path']; ?></td>
    <td><?=  $config['value']; ?></td>
  </tr>
        <?php $i++; ?>
    <?php endforeach ?>
</tbody>
</table>
<?php endif;?>
