<?php
/** @var \ADM\QuickDevBar\Block\Tab\Content\Request $block */
?>

<?php if(!$block->getRequestData()) {

    echo 'An error occurred generating toolbar data';
    return;
}
?>


<table class="qdb_table_2col">
<?php foreach ($block->getRequestData() as $data):?>
    <tr>
        <th><?=  $data['name'];?></th>
        <td><?=  $block->formatValue($data);?>
    </td>
<?php endforeach;?>
</table>
