<?php
/** @var  $block \ADM\QuickDevBar\Block\Tab\Panel */

?>

<table  class="qdb_table">
    <tr>
        <th>Change QDB theme</th>
        <td>
            <select onChange="switchTheme(this);">
                <option value="">Standard</option>
                <option value="dark">Dark</option>
                <option value="kawaii">Kawaii UwU</option>
            </select>
        </td>

        <td id="process-template_hints_storefront"></td>
    </tr>
    <tr>
        <th>Template Path Hints for Storefront</th>
        <td><button type="button" onClick="actionConfig('template_hints_storefront', 'toggle', 'auto')" class="qdb-action">Toggle</button></td>
        <td id="process-template_hints_storefront"></td>
    </tr>
    <tr>
        <th>Template Path Hints for Admin</th>
        <td><button type="button" onClick="actionConfig('template_hints_admin', 'toggle', 'auto')" class="qdb-action">Toggle</button></td>
        <td id="process-template_hints_admin"></td>
    </tr>
    <tr>
        <th>Add Block Names to Hints</th>
        <td><button type="button" onClick="actionConfig('template_hints_blocks', 'toggle', 'auto')" class="qdb-action">Toggle</button></td>
        <td id="process-template_hints_blocks"></td>
    </tr>
    <tr>
        <th>Translate inline</th>
        <td><button type="button" onClick="actionConfig('translate', 'toggle', 'auto')" class="qdb-action">Toggle</button></td>
        <td id="process-translate"></td>
    </tr>
    <tr>
        <th>Flush Cache Storage</th>
        <td><button type="button" onClick="actionCache()" class="qdb-action">Flush</button></td>
        <td id="process-cache"></td>
    </tr>
    <tr>
        <th>Set developer admin config</th>
        <td><button type="button" onClick="actionConfig('devadmin', 'toggle', 'default')" class="qdb-action">Set</button></td>
        <td id="process-devadmin"></td>
    </tr>
</table>



<script type="text/javascript">
    'use strict';

    function switchTheme(e) {
        let qdbTheme = e.querySelector('option:checked').value;
        document.getElementById('qdb-bar').setAttribute('data-theme', qdbTheme);
    }

    function actionConfig(key, value, scope) {
        let target = 'process-' + key;
        window.quickDevBar.showLoader(target);

        let params = new URLSearchParams({isAjax: 1});
        params.append("config[key]", key);
        params.append("config[value]", value);
        params.append("config[scope]", scope);

        window.quickDevBar.qdbFetchPromise('quickdevbar/action/configUpdate?' + params.toString()).then(html => {
            document.getElementById(target).innerHTML = html;
            console.log(html);
        });
    }

    function actionCache()
    {
        var target =  'process-cache';
        window.quickDevBar.showLoader(target);

        window.quickDevBar.qdbFetchPromise('quickdevbar/action/cache').then(html => {
            document.getElementById(target).innerHTML = html;
        });
    }


</script>

