<?php
/** @var  $block \ADM\QuickDevBar\Block\Tab\Panel */

?>

<table  class="qdb_table">
    <tr>
        <th>Change QDB theme</th>
        <td>
            <select id="qdb-theme-selector">
                <option value="">Standard</option>
                <option value="dark">Dark</option>
                <option value="kawaii">Kawaii UwU</option>
            </select>
        </td>
        <td id="process-template_hints_storefront"></td>
    </tr>
    <tr>
        <th>Template Path Hints for Storefront</th>
        <td><button type="button" data-qdbAction='{"path":"action/configUpdate", "params":{"config[key]":"template_hints_storefront"}, "target":"process-template_hints_storefront"}'   class="qdb-action">Toggle</button></td>
        <td id="process-template_hints_storefront"></td>
    </tr>
    <tr>
        <th>Template Path Hints for Admin</th>
        <td><button type="button" data-qdbAction='{"path":"action/configUpdate", "params":{"config[key]":"template_hints_admin"}, "target":"process-template_hints_admin"}'   class="qdb-action">Toggle</button></td>
        <td id="process-template_hints_admin"></td>
    </tr>
    <tr>
        <th>Add Block Names to Hints</th>
        <td><button type="button" data-qdbAction='{"path":"action/configUpdate", "params":{"config[key]":"template_hints_blocks"}, "target":"process-template_hints_blocks"}'   class="qdb-action">Toggle</button></td>
        <td id="process-template_hints_blocks"></td>
    </tr>
    <tr>
        <th>Translate inline</th>
        <td><button type="button" data-qdbAction='{"path":"action/configUpdate", "params":{"config[key]":"translate"}, "target":"process-translate"}'   class="qdb-action">Toggle</button></td>
        <td id="process-translate"></td>
    </tr>
    <tr>
        <th>Flush Cache Storage</th>
        <td><button type="button" data-qdbAction='{"path":"action/cache", "target":"process-cache"}'   class="qdb-action">Flush</button></td>
        <td id="process-cache"></td>
    </tr>
</table>

<script type="text/javascript">
    'use strict';
    document.addEventListener('QDBBarLoaded', (event) => {
        let themeSelector = document.getElementById('qdb-theme-selector');
        let userThemeOption = themeSelector.querySelector('option[value="'+window.quickDevBar.loadUserData('qdb_theme')+'"]');
        if(userThemeOption!==null) {
            userThemeOption.selected="selected"
        }
        themeSelector.addEventListener('change', () => window.quickDevBar.switchTheme(themeSelector.querySelector('option:checked').value));
    });
</script>
