<?php
/** @var  $block \ADM\QuickDevBar\Block\Tab\Panel */
?>
<a href="https://github.com/vpietri/magento2-developer-quickdevbar""><img style="position: absolute; top: 0; right: 0; border: 0;"  decoding="async" width="149" height="149" src="https://github.blog/wp-content/uploads/2008/12/forkme_right_red_aa0000.png?resize=149%2C149" class="attachment-full size-full" alt="Fork me on GitHub" loading="lazy" data-recalc-dims="1"></a>


<span><b><?=  $block->getModuleName()?></b> (version <?=  $block->getModuleVersion()?>)</span>

</br>
<p>In order to use this toolbar on a remote server you should either specify allowed IP or set a part of your http header in the config.</p>
<p>Any feedback and idea to improve this toolbar will be appreciate so get in touch via the <a target="_blank" href="https://github.com/vpietri/magento2-developer-quickdevbar/issues">issue tracker</a> on GitHub.</p>
