<?php
?>
<a href="https://github.com/vpietri/magento2-developer-quickdevbar"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/365986a132ccd6a44c23a9169022c0b5c890c387/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png"></a>

<p>
<span><b><?php echo $block->getModuleName()?></b> (version <?php echo $block->getModuleVersion()?>)</span>
<!-- Place this tag in your head or just before your close body tag. -->
<!-- <script async defer src="https://buttons.github.io/buttons.js"></script> -->
&nbsp;&nbsp;&nbsp;
<!-- Place this tag where you want the button to render. -->
<a aria-label="Watch vpietri/magento2-developer-quickdevbar on GitHub" data-count-aria-label="# watchers on GitHub" data-count-api="/repos/vpietri/magento2-developer-quickdevbar#subscribers_count" data-count-href="/vpietri/magento2-developer-quickdevbar/watchers" data-icon="octicon-eye" href="https://github.com/vpietri/magento2-developer-quickdevbar" class="github-button">Watch</a>
&nbsp;
<!-- Place this tag where you want the button to render. -->
<a aria-label="Star vpietri/magento2-developer-quickdevbar on GitHub" data-count-aria-label="# stargazers on GitHub" data-count-api="/repos/vpietri/magento2-developer-quickdevbar#stargazers_count" data-count-href="/vpietri/magento2-developer-quickdevbar/stargazers" data-icon="octicon-star" href="https://github.com/vpietri/magento2-developer-quickdevbar" class="github-button">Star</a>
</p>
</br>
<p>In order to use this toolbar on a remote server you should either specify allowed IP or set a part of your http header in the config.</p>
<p>Any feedback and idea to improve this toolbar will be appreciate so get in touch via the <a href="https://github.com/vpietri/magento2-developer-quickdevbar/issues">issue tracker</a> on GitHub.</p>
<script type="text/javascript">
<!--
require([
         'jquery'
     ], function($){

        var loaded = false;
        $('div.qdb-container').on("quickdevbartabsbeforeactivate", function(event, data) {
            var tabId = data.newPanel ? data.newPanel.attr( "id" ) : false;
            if (!loaded && tabId=='panel-qdb-tab-help') {
                console.log('panel-qdb-tab-help');
                $.getScript("https://buttons.github.io/buttons.js");
                loaded = true;
            }
        });
});
//-->
</script>