<?php
?>
<a href="https://github.com/vpietri/magento2-developer-quickdevbar"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/365986a132ccd6a44c23a9169022c0b5c890c387/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png"></a>

<p>
<span><b><?php echo $block->getModuleName()?></b> (version <?php echo $block->getModuleVersion()?>)</span>

</br>
<p>In order to use this toolbar on a remote server you should either specify allowed IP or set a part of your http header in the config.</p>
<p>Any feedback and idea to improve this toolbar will be appreciate so get in touch via the <a href="https://github.com/vpietri/magento2-developer-quickdevbar/issues">issue tracker</a> on GitHub.</p>