<?php
/** @var  $block \ADM\QuickDevBar\Block\Tab\Panel */
?>
<button type="button" onClick="javascript:resetAllLogs();return false;" class="qdb-action">Reset all Logs</button>
<br/>
<br/>
<?php foreach ($block->getLogFiles() as $logKey => $logFile):?>
    <h3><?=  $logFile['name'] ?>&nbsp;<button type="button" onClick="javascript:resetLog('<?=  $logKey ?>');return false;" class="qdb-action">Reset</button></h3>
    Tail the <?=  $block->getTailLines() ?> last lines
    <pre id= "content-<?=  $logKey ?>">
    </pre>
    <br/>
<?php endforeach;?>
<div id='log-loader' style="display:none"><?=  $block->getHtmlLoader()?></div>

<script type="text/javascript">

    const logFiles = <?=  $block->getJsonLogFiles() ?>;
    let loaded = false;

    document.addEventListener('tabbis_pane_activate', (event) => {
        if (!loaded && event.detail.tab.getAttribute('id')=='qdb-tab-log') {
            for (let key in logFiles) {
                if (logFiles[key].size>0) {
                    loadLogContent(key);
                }
            }
            loaded = true;
        }
    });

    loadLogContent = function(key)
    {
        let target =  'content-' +  key ;
        let params = new URLSearchParams({isAjax:1,log_key:key,tail:<?=  $block->getTailLines(); ?>});
        window.quickDevBar.qdbFetchPromise('quickdevbar/log/view/?' + params.toString()).then(html => {
            document.getElementById(target).innerHTML = html;
        });
    };

    resetAllLogs = function()
    {
        for (let key in logFiles) {
            resetLog(key);
        }
    };

    resetLog = function(key)
    {
        let target =  'content-' +  key ;
        let params = new URLSearchParams({isAjax:1,log_key:key});
        window.quickDevBar.qdbFetchPromise('quickdevbar/log/reset/?' + params.toString()).then(html => {
            document.getElementById(target).innerHTML = html;
        });
    };

</script>
