<?php
/** @var ADM\QuickDevBar\Block\Tab\Content\Sql $block */

use ADM\QuickDevBar\Helper\Cookie;
use ADM\QuickDevBar\Plugin\Zend\DbAdapter;

?>
<?php if ($block->getAllQueries()): ?>
<table class="qdb_table_2col">
    <tbody>
      <tr>
        <th><?php echo __('Statistics'); ?></th>
        </td>
        <td>
          <?=  sprintf(
              '%s queries in %s (average time: %s) - %s queries/second',
              $block->getTotalNumQueries(),
              $block->formatSqlTime($block->getTotalElapsedSecs()),
              $block->formatSqlTime($block->getAverage()),
              $block->getNumQueriesPerSecond()
          ); ?>
        </td>
      </tr>

  <tr>
    <th></th>
    <td>
      <?=  sprintf(
          '%s SELECT - %s INSERT - %s UPDATE - %s DELETE - %s TRANSACTION',
          $block->getTotalNumQueriesByType(Zend_Db_Profiler::SELECT),
          $block->getTotalNumQueriesByType(Zend_Db_Profiler::INSERT),
          $block->getTotalNumQueriesByType(Zend_Db_Profiler::UPDATE),
          $block->getTotalNumQueriesByType(Zend_Db_Profiler::DELETE),
          $block->getTotalNumQueriesByType(Zend_Db_Profiler::TRANSACTION)
      ); ?>
    </td>
  </tr>
  <tr>
    <th><?=  __('Longest'); ?></th>
    <td>
      <?=  $block->formatSql($block->getLongestQuery()); ?>
    </td>
  </tr>
  <tr>
    <th></th>
    <td>
      <span>(<?=   $block->formatSqlTime($block->getLongestQueryTime()); ?>)</span>
    </td>
  </tr>
    <tr>
        <th>
            <button type="button" data-qdbAction='{"path":"action/cookie", "params":{"qdbName":"<?= Cookie::COOKIE_NAME_PROFILER_ENABLED?>","qdbToggle":true}}' class="qdb-action"><?= $block->getButtonProfilerLabel() ?></button>
        </th>
        <td>
            <?php if($block->getProfilerEnabled()):?>
                <button type="button" data-qdbAction='{"path":"action/cookie", "params":{"qdbName":"<?= Cookie::COOKIE_NAME_PROFILER_BACKTRACE_ENABLED?>","qdbToggle":true}}' class="qdb-action"><?= $block->getButtonProfilerBactraceLabel() ?></button>
            <?php endif;?>
        </td>
    </tr>
    </tbody>
</table>

<div class="qdb-panel">
    <table class="qdb_table striped filterable sortable tablesorter grade">
    <thead>
        <tr>
            <th>#</th>
            <th class="{sorter: false}">SQL</th>
            <th class="{sorter: 'text'}">Args</th>
            <?php if($block->getProfilerBacktraceEnabled()): ?>
                <th class="{sorter: false}">Bt</th>
            <?php endif; ?>
            <th class="{sorter: 'digit'}">Time</th>

        </tr>
    </thead>
    <tbody>
    <?php
      $i = 0;
      foreach ($block->getAllQueries() as $i => $query): ?>
        <tr class="<?php echo  $query['grade']; ?>">
          <td><?php echo $i;?></td>
          <td class="sqlquery"><?php echo $block->formatSql($query['sql']); ?></td>
          <td class="sqlargs"><?php echo $block->formatParams($query['params']); ?></td>

            <?php if($block->getProfilerBacktraceEnabled()): ?>
                <td><?php echo  $block->formatSqlTrace($query['bt'])  ?></td>
            <?php endif; ?>
            <td class="sqltimer"><?php echo  $block->formatSqlTime($query['time']); ?></td>
        </tr>
        <?php $i++; ?>
      <?php endforeach ?>
    </tbody>
    </table>
</div>

<?php else:?>
SQL profiler is not active<br/>
You can use command line
<pre>bin/magento dev:quickdevbar:enable</pre>
and use a specific profiler with backtrace
<pre>bin/magento dev:quickdevbar:enable --sql-profiler</pre>
<strong>OR</strong><br/>
set a new key for $config array in file app/etc/env.php<br/>
<pre>$config[db][connection][default][profiler] = 1</pre>
<strong>OR</strong><br/>
Dynamically enable profiler for your session (cookie qdb_db_profiler_ebnabled)<br/>
<button type="button" data-qdbAction='{"path":"action/cookie", "params":{"qdbName":"<?= Cookie::COOKIE_NAME_PROFILER_ENABLED?>","qdbToggle":true}}' class="qdb-action"><?= $block->getButtonProfilerLabel() ?></button><br/>
Page need to be refresh
<?php  endif ?>
