<?php
?>
<div id="qdn-profiler-container">
<?php echo __('Cannot find profiler table or profiler is not enabled.'); ?>
<br/>
You have to add a SetEnv MAGE_PROFILER "html" to your .htaccess (do not use "csvfile" nor "firebug" to have profiler displayed in tab).
Be careful with .htacces directive you can have $_SERVER['REDIRECT_MAGE_PROFILER'] set instead of  $_SERVER['MAGE_PROFILER'] prefer apache2.conf.
</div>

<script type="text/javascript">

require([
    'jquery'
], function($){
    var tableProfiler = $('table').last();
    var captionProfiler = tableProfiler.find('caption').html();

    if (captionProfiler && captionProfiler.match('Code Profiler ')) {
        $('#qdn-profiler-container').html('');
        tableProfiler.removeAttr('border').removeAttr('cellspacing').removeAttr('cellpadding');
        tableProfiler.addClass('qdn_table');
        tableProfiler.addClass('filterable');
        tableProfiler.appendTo($('#qdn-profiler-container'));
    }
});
</script>