<?php
$_website = $block->getWebsite();
$_store = $this->getStore();
?>

<table class="qdn_table_2col">
  <tr>
    <th><?php echo __('Website Id'); ?></th>
    <td><?php echo $_website->getId(); ?></td>
  </tr>
  <tr>
    <th><?php echo __('Website Name'); ?></th>
    <td><?php echo $_website->getName(); ?></td>
  </tr>
  <tr>
    <th><?php echo __('Store Id'); ?></th>
    <td><?php echo $_store->getId(); ?></td>
  </tr>
  <tr>
    <th><?php echo __('Store Name'); ?></th>
    <td><?php echo $_store->getName(); ?></td>
  </tr>
  <tr>
    <th><?php echo __('Store Code'); ?></th>
    <td><?php echo $_store->getCode(); ?></td>
  </tr>
</table>